# Generated by Django 4.2.10 on 2024-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="title", field=models.CharField(max_length=300),
        ),
    ]
