# Generated by Django 5.0.2 on 2025-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_images'),
        ),
    ]
